base:
  port: 8080
  headOptions:
    title: 'MPIS (dev)'
    desc:  'A sample typed mean (Angular5, nest.js, typeorm, mongodb) project'
    keywords: 'Angular, node.js, nest.js, express.js, mongodb, typescript'
    author: 'Vladimir Ovsyukov (me@ovsyukov.info)'

database:
  host: 'mlab host here'
  port: 27017
  db: 'dab_name'
  creds:
    username: 'test'
    password: 'test'

secrets:
  jwtStr: 's0meSupperS9cur9Str1ng'
  fb:
    appId: '1825033960857449'
    appSecret: 'SomeStirngWhichIsTheFacebookAppSecret'
